
services:

  api:
    build:
      context: ../../
    container_name: api
    command: uvicorn api.main:app --host 0.0.0.0 --port ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ../../output:/app/output
    environment:
      - PICASSO=${PICASSO}
      - CHAT_MODEL=${CHAT_MODEL}
      - EMBED_MODEL=${EMBED_MODEL}
      - VISION_MODEL=${VISION_MODEL}
      - VECTOR_DB_URL=${VECTOR_DB_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - qdrant
      - redis

  worker:
    build:
      context: ../../
    container_name: worker
    command: python workers/worker.py
    environment:
      - VECTOR_DB_URL=${VECTOR_DB_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAT_MODEL=${CHAT_MODEL}
      - EMBED_MODEL=${EMBED_MODEL}
      - VISION_MODEL=${VISION_MODEL}
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "${QDRANT_PORT}:6333"
      - "${QDRANT_GRPC_PORT}:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
  redis_data: